### ISSUE TITLE
gople/ch1/e1.4/dup2.go

### ISSUE THREAD

**Issue by amosnothing** [PieerePi/gople#1]
这里是不是有 bug，如果不同的文件之间，行存在重复的

比如 a.txt 有行 123，b.txt 也有行 123，答案的写法是将行的内容跟文件绑定在一起

**Comment by PieerePi** [comment]
我写了两个版本，你说的这个意思，在这儿。:-)
gople/ch1/e1.4-2/dup2.go

**Comment by PieerePi** [comment]
> 我写了两个版本，你说的这个意思，在这儿。:-)
> gople/ch1/e1.4-2/dup2.go
